apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: posthog 
  namespace: argocd 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default 
  source:
    chart: posthog 
    repoURL: https://posthog.github.io/charts-clickhouse/ 
    targetRevision: 7.3.0 
    helm:
      releaseName: posthog
  destination:
    server: https://kubernetes.default.svc
    namespace: posthog 