apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: posthog 
  namespace: argocd 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default 
  source:
    chart: posthog 
    repoURL: https://posthog.github.io/charts-clickhouse/ 
    targetRevision: 7.3.0 
    helm:
      releaseName: posthog
      values: |
        cloud: "do"
        deploymentType: "DigitalOcean 1-click"
        ingress:
          nginx:
            enabled: true
            redirectToTLS: false
          letsencrypt: false
        clickhouseOperator:
          useNodeSelector: true
        web:
          secureCookies: false
  destination:
    server: https://kubernetes.default.svc
    namespace: posthog 